
baseurl: "https://uncertainty-cv.github.io/2025/"
color-scheme: "#1a2090" #the scheme can be any HEX code like "#334279"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache

title: "4th Workshop on Uncertainty Quantification for Computer Vision"
subtitle: "[CVPR 2025 Workshop](https://cvpr.thecvf.com/Conferences/2025) on 11th June 2025"

shorttitle: "UNCV Workshop @ CVPR 2025"
information: "CVPR 2025 Workshop on Uncertainty Quantification for Computer Vision." 

organizers: "UNCV Organizers"

deadlines:
  - item: Submission deadline
    date: "<s>March 14th, 2025</s> <b>Extended until: March 20th, 2025</b>"
  
  - item: Notification of acceptance
    date: "<s>April 1st, 2025</s>"

  - item: Camera-ready deadline
    date: "<s>April 7th, 2025</s>"


challengedl:
  - item: BRAVO Challenge 2025 launch. Submission server is open
    date: 01/05/2025

  - item: 1st submission deadline for CVPR 2025 edition
    date: 06/06/2025

  - item: BRAVO Challenge session at UNCV
    date: 11/06/2025

  - item: 2nd submission deadline to conclude BRAVO 2025 at ICCV 2025
    date: TBD

  - item: Whitepaper contribution deadline
    date: TBD
