
baseurl: "https://uncertainty-cv.github.io/2025/"
color-scheme: "#1a2090" #the scheme can be any HEX code like "#334279"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache

title: "4th Workshop on Uncertainty Quantification for Computer Vision"
subtitle: "[CVPR 2025 Workshop](https://cvpr.thecvf.com/Conferences/2025)"

shorttitle: "UNCV Workshop @ CVPR 2025"
information: "CVPR 2025 Workshop on Uncertainty Quantification for Computer Vision." 

organizers: "UNCV Organizers"

deadlines:
  - item: Submission deadline
    date: March 14th, 2025
  
  - item: Notification of acceptance
    date: April 1st, 2025

  - item: Camera-ready deadline
    date: April 7th, 2025


# challengedl:
#   - item: BRAVO Challenge 2024 launch, data and code available for download
#     date: 17/06/2024
#
#   - item: Submission server open
#     date: 01/07/2024
#
#   - item: Submissions deadline
#     date: 23/08/2024
#
#   - item: Technical report deadline
#     date: 27/08/2024
